export const clients = [
    {
        id: "#123",
        name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Active",
        action: ''
    },
    {
        id: "#193",
        name: "John Smith",
        key: '2',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Inactive",
        action: ''
    },
    {
        id: "#124",
        name: "John Smith",
        key: '3',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Active",
        action: ''
    },
    {
        id: "#121",
        name: "John Smith",
        key: '4',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Inactive",
        action: ''
    },
    {
        id: "#122",
        name: "John Smith",
        key: '5',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Active",
        action: ''
    },
    {
        id: "#125",
        name: "John Smith",
        key: '6',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Active",
        action: ''
    },
    {
        id: "#126",
        name: "John Smith",
        key: '7',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        lastActive: "12/09/2022,10:00:02",
        status: "Active",
        action: 'yup'
    },
]

export const membershipDetail = [
    {
        membership_id: "#123",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Active",
        action: ''
    },
    {
        membership_id: "#193",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '2',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Inactive",
        action: ''
    },
    {
        membership_id: "#124",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '3',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Active",
        action: ''
    },
    {
        membership_id: "#121",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '4',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Inactive",
        action: ''
    },
    {
        membership_id: "#122",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '5',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Active",
        action: ''
    },
    {
        membership_id: "#125",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '6',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Active",
        action: ''
    },
    {
        membership_id: "#126",
        membership_period : "6 months",
        amount : "SGD 100.00",
        name: "John Smith",
        key: '7',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        activation_date: "12/09/2022",
        expiry_date:"19/08/2022",
        status: "Active",
        action: 'yup'
    },
]

export const membershipPayment = [
    {
        payment_id: "#123",
        name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Paid",
        action: ''
    },
    {
        payment_id: "#193",
        name: "John Smith",
        key: '2',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Pending",
        action: ''
    },
    {
        payment_id: "#124",
        name: "John Smith",
        key: '3',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Paid",
        action: ''
    },
    {
        payment_id: "#121",
        name: "John Smith",
        key: '4',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Pending",
        action: ''
    },
    {
        payment_id: "#122",
        name: "John Smith",
        key: '5',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Paid",
        action: ''
    },
    {
        payment_id: "#125",
        name: "John Smith",
        key: '6',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Paid",
        action: ''
    },
    {
        payment_id: "#126",
        name: "John Smith",
        key: '7',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        membershipType: "Plan 1",
        payment_amount:"SGD 100.00",
        payment_date: "12/09/2022",
        expiry_date:"19/08/2022",
        payment_mode:"Stripe",
        status: "Paid",
        action: 'yup'
    },
]
export const membershipEventBooking = [
    {
        id: "#123",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png",
        event_time:"10/10/2000",
        age:"23",
        course_role:"2"
    },
    {
        id: "#125",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456",
        email: "jane@gmail.com",
        status: "Active",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar 2.png",
        event_time:"10/10/1994",
        age:"20",
        course_role:"1"
    },
    {
        id: "#127",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png",
        event_time:"10/10/2000",
        age:"23",
        course_role:"2"
    },
    {
        id: "#129",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456",
        email: "jane@gmail.com",
        status: "Active",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar 2.png",
        event_time:"10/10/1994",
        age:"20",
        course_role:"1"
    },
    {
        id: "#132",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png",
        event_time:"10/10/2000",
        age:"23",
        course_role:"2"
    },
    {
        id: "#45",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456",
        email: "jane@gmail.com",
        status: "Active",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar 2.png",
        event_time:"10/10/1994",
        age:"20",
        course_role:"1"
    },
    {
        id: "#312",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png",
        event_time:"10/10/2000",
        age:"23",
        course_role:"2"
    },
    {
        id: "#523",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456",
        email: "jane@gmail.com",
        status: "Active",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar 2.png",
        event_time:"10/10/1994",
        age:"20",
        course_role:"1"
    },
]

export const membershipFacilityBooking = [
    {
        id: "#123",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },
    {
        id: "#122",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },
    {
        id: "#124",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },
    {
        id: "#125",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },
    {
        id: "#127",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },
    {
        id: "#128",
        avatar: "/img/avatar3.png",
        name:"Workplace Safety and Health in Construction Sites",
        Course_category: 'Safety Courses',
        date : "10 Mar 2023 10:00-7:00Pm",
        venue: "Woodland",

        enroll:"25",
        assignment: "10",
        assesment:"2",
        status: 'active'
    },

]

export const membershipRequest = [
    {
        id: "#123",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png"
    },
    {
        id: "#125",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456789",
        email: "jane@gmail.com",
        status: "Active",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Teacher",
        avatar:"/img/Avatar 2.png"
    },
    {
        id: "#121",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png"
    },
    {
        id: "#120",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456789",
        email: "jane@gmail.com",
        status: "Inactive",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Teacher",
        avatar:"/img/Avatar 2.png"
    },
    {
        id: "#129",
        applicant_name: "John Smith",
        key: '1',
        phone: "+65 123456789",
        email: "johnsmith@gmail.com",
        status: "Active",
        action: '',
        gender:"male",
        nationality:"Singapore",
        role:"Manager",
        avatar:"/img/Avatar.png"
    },
    {
        id: "#130",
        applicant_name: "Jane Cooper",
        key: '1',
        phone: "+65 123456789",
        email: "jane@gmail.com",
        status: "Inactive",
        action: '',
        gender:"female",
        nationality:"Singapore",
        role:"Teacher",
        avatar:"/img/Avatar 2.png"
    },
  
]

export const facilityList = [
    {
        facility_id : "#123",
        facility_type : "Indor Hall",
        facility_name : "Event Facility",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Available",
        action : ""
    },
    {
        facility_id : "#124",
        facility_type : "Open Garden",
        facility_name : "Singing Club",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Available",
        action : ""
    },
    {
        facility_id : "#125",
        facility_type : "Indor Hall",
        facility_name : "Event Facility",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Close",
        action : ""
    },
    {
        facility_id : "#126",
        facility_type : "Indor Hall 2",
        facility_name : "Sports Facility",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Available",
        action : ""
    },
    {
        facility_id : "#127",
        facility_type : "Indor Hall",
        facility_name : "Event Facility",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Close",
        action : ""
    },
    {
        facility_id : "#128",
        facility_type : "Pool area",
        facility_name : "Resurant & Bar",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Available",
        action : ""
    },
    {
        facility_id : "#129",
        facility_type : "Indor Hall",
        facility_name : "Event Facility",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Available",
        action : ""
    },
    {
        facility_id : "#121",
        facility_type : "Indor Hall",
        facility_name : "Sports Club",
        business_hrs : "Mon-Fri, 10:00-8:00Pm",
        no_of_bookings : 20,
        total_revenue : "SGD 10000.00",
        status : "Close",
        action : ""
    },
]
